name: CI

on:
  pull_request:
    branches: ["cloud-engine-on-release-7.5"]

jobs:
  build-amd64:
    name: Build on AMD64
    runs-on: amd64
    timeout-minutes: 180
    outputs:
      image: tiflash-cse:${{ github.sha }}-amd64
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GIT_ACTION_BOT }}
          fetch-depth: 0
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: release-centos7-llvm/dockerfiles/Dockerfile-tiflash-cse-multiarch
          platforms: "linux/amd64"
          push: false
          tags: hub.pingcap.net/sunxiaoguang/serverless/tiflash:${{ github.sha }}-amd64
